name: swp409
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_icons: ^1.0.0+1
  google_maps_flutter:
  google_fonts:
  http: ^0.12.0+4
  geolocator:
  analyzer:
  json_annotation: ^3.0.1
  table_calendar: ^2.3.3
  flutter_svg: ^0.21.0+1
  provider: ^5.0.0
dev_dependencies:
  json_serializable: ^3.3.0
  pedantic:
  build_runner: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/json/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300