name: swp409
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  smooth_star_rating: ^1.1.1
  flutter_icons: ^1.0.0+1
  google_maps_flutter: ^2.0.6
  google_fonts:
  http: ^0.13.1
  geolocator:
  analyzer:
  json_annotation: ^4.0.1
  table_calendar: ^3.0.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  image_picker: ^0.8.0+1
  autocomplete_textfield: ^1.7.3
  flutter_polyline_points: ^1.0.0
  flutter_local_notifications:
  rxdart:
  dio: ^4.0.0
  fluttertoast: ^8.0.6
  multi_image_picker: ^4.8.0
  flutter_secure_storage: ^4.2.0
  flutter_dotenv: ^5.0.0
  flutter_typeahead: ^3.1.3
  cached_network_image: ^3.0.0
  modal_progress_hud: ^0.1.3
  date_format: ^2.0.2
  cookie_jar: ^3.0.1
  dio_cookie_manager:
  geocoding:
  flutter_google_places:
  address_search_field: ^4.0.1

dev_dependencies:
  json_serializable: ^4.1.3
  pedantic:
  build_runner:
  flutter_config: ^2.0.0
  places_service: ^0.1.0+2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/json/
    - .env
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
